/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "implementation-test.check" instead.
 */

#include <check.h>

#line 1 "implementation-test.check"
#include "implementation.h"


START_TEST(testForConvertingRomanToNumber)
{
#line 5
	ck_assert_int_eq(romanToNumber("I"),1);

}
END_TEST

START_TEST(testForAdditionOfTwoRomanNumbers)
{
#line 8
	ck_assert_str_eq(romanAddition("II","I"),"II");

}
END_TEST

START_TEST(testForConvertingNumberToRoman)
{
#line 11
	ck_assert_str_eq(numberToRoman(1),"I");


}
END_TEST

START_TEST(testForSubtractionOfTwoRomanNumbers)
{
#line 15
	ck_assert_str_eq(romanSubtraction("II","I"),"I");

}
END_TEST

int main(void)
{
    Suite *s1 = suite_create("Core");
    TCase *tc1_1 = tcase_create("Core");
    SRunner *sr = srunner_create(s1);
    int nf;

    suite_add_tcase(s1, tc1_1);
    tcase_add_test(tc1_1, testForConvertingRomanToNumber);
    tcase_add_test(tc1_1, testForAdditionOfTwoRomanNumbers);
    tcase_add_test(tc1_1, testForConvertingNumberToRoman);
    tcase_add_test(tc1_1, testForSubtractionOfTwoRomanNumbers);

    srunner_run_all(sr, CK_ENV);
    nf = srunner_ntests_failed(sr);
    srunner_free(sr);

    return nf == 0 ? 0 : 1;
}
